name: Python API CI

on: [push, pull_request]

jobs:
  build-from-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install From Source
        run: |
          python -m pip install --use-feature=in-tree-build ./PythonAPI
      - name: Run Simple Test Cases
        run: |
          python tests/test_cases.py

  build-from-source-prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install From Source
        run: |
          python -m pip install --pre --use-feature=in-tree-build ./PythonAPI
      - name: Run Simple Test Cases
        run: |
          python tests/test_cases.py

  build-from-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install From Distribution
        run: |
          python -m pip install build
          python -m build --sdist ./PythonAPI
          python -m pip install --progress-bar off ./PythonAPI/dist/*.tar.gz
      - name: Run Simple Test Cases
        run: |
          python tests/test_cases.py