name: Python API CI

on: [push, pull_request]

jobs:
  build-from-source:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install From Source
        run: |
          python -m pip install --upgrade pip
          python -m pip install --use-feature=in-tree-build ./PythonAPI
      - name: Run Simple Test Cases
        run: |
          python tests/test_cases.py

  build-from-source-prerelease:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install From Source
        run: |
          python -m pip install --upgrade pip
          python -m pip install --pre --use-feature=in-tree-build ./PythonAPI
      - name: Run Simple Test Cases
        run: |
          python tests/test_cases.py

  build-from-sdist:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install From Distribution
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build --sdist ./PythonAPI
          python -m pip install --progress-bar off ./PythonAPI/dist/*.tar.gz
      - name: Run Simple Test Cases
        run: |
          python tests/test_cases.py

